name: MTB
on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:
concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true

jobs:
  earthly:
    runs-on:
      - ubuntu-latest
      #- self-hosted
    steps:
      - uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: "latest"
      - uses: actions/checkout@v2
      - name: Docker login # to avoid dockerhub rate-limiting
        run: echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | docker login ghcr.io --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        #run: docker login https://ghcr.io --username "${{ secrets.DOCKERHUB_USERNAME }}" --password "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}"
      - name: what version is installed?
        run: earthly --version
      - uses: actions/checkout@v3.5.0
        with:
          fetch-depth: 20
          lfs: true
      - run: earthly config global.disable_log_sharing true
      - run: earthly +build-all
